name: Alexa Shopping List Sync
version: '2502.053'
slug: alexa_shopping_bridge
description: Alexa Shopping List synchronisation server
url: "https://github.com/debodt/HASS-Addons"
arch:
  - aarch64
  - amd64
image: "debodt/alexa-shopping-bridge-server:latest-arm64"
startup: "services"
ports:
  8765/tcp: 8765
map:
  - type: addon_config
    read_only: false
    path: /config
