name: Alexa Shopping bridge
version: 'latest'
slug: alexa_shopping_bridge_server
description: Alexa Shopping Bridge
url: "https://github.com/debodt/HASS-Addons/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "debodt/alexa-shopping-bridge-server"
startup: "services"
ports:
  8765/tcp: 8765
map:
  - type: addon_config
    read_only: false
    path: /config
